// flow-typed signature: b3e7b755433e2d8213e09d980e89d4fa
// flow-typed version: <<STUB>>/sandwich-stream_v1.0.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sandwich-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sandwich-stream' {
  declare export class SandwichStream {
    constructor(options?: {}): this;
    add(part: any): void;
  }
}
