blank_issues_enabled: false
contact_links:
  - name: Question (via Telegram groups)
    url: https://github.com/telegraf/telegraf/blob/develop/docs/README.md#resources
    about: Ask and answer questions about Telegraf
contact_links:
  - name: Question (via GitHub Discussions)
    url: https://github.com/telegraf/telegraf/discussions/categories/q-a
    about: Ask and answer questions about Telegraf
