name: Release

on:
  push:
    tags:
      - v6.*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2
    - run: npm ci
    - run: npm run build:docs
    - name: Make GitHub links absolute
      run: |
        shopt -s globstar;
        sed \
          --in-place \
          --expression='s:/develop/docs/:/${{ github.sha }}/docs/:g' \
          --expression='s:<img src="docs/assets/:<img src="media/:g' \
          docs/build/**/*.html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        # for v3.html and perhaps CNAME
        keep_files: true
    - name: Publish to npm
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
